_wandb:
    value:
        cli_version: 0.19.3
        code_path: code/scripts/td3_tower.py
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.15
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
env_name:
    value: JengaTower3-v3
policy_type:
    value: MultiInputPolicy
total_timesteps:
    value: 5e+07
